mongouri: mongodb://localhost:27017/pingatus?timeoutMS=5000

debug: true

webapi:
  listenaddr: :8080

httppoint:
  - name: home
    url: https://twst.dev
    status: 200
    timeout: 3s
    interval: 5s