mongouri: mongodb://localhost:27017/pingatus?timeoutMS=5000

debug: true

webapi:
  listenaddr: :8080

httppoint:
  - name: home
    url: http://195.138.72.247
    status: 200
    timeout: 3s
    interval: 1m