mongouri: mongodb://localhost:27017/pingatus?timeoutMS=5000

debug: true

webapi:
  listenaddr: :8080
  assetsdir: ./assets

httppoint:
  - name: home
    url: https://google.com
    status: 200
    timeout: 3s
    interval: 1m

icmppoint:
  - name: internet
    ip: 8.8.8.8
    packetcount: 3
    interval: 1m

notifier:
  type: telegram
  tgtoken: telegram_bot_token
  tgchatid: telegram_chat_id