mongouri: mongodb://localhost:27017/pingatus?timeoutMS=5000

debug: true

webapi:
  listenaddr: :8080
  assetsdir: ./assets

endpoints:
  - name: home
    address: https://google.com
    status: 200
    timeout: 3s
    interval: 1m
    type: http

  - name: internet
    address: 8.8.8.8
    packetcount: 3
    interval: 1m
    type: icmp

notifier:
  type: telegram
  tgtoken: telegram_bot_token
  tgchatid: telegram_chat_id