networks:
  mynet:
    driver: bridge

services:
  db:
    image: mongo:7.0
    restart: always
    networks:
      - mynet
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  app:
    image: pingatus:latest
    restart: always
    networks:
      - mynet
    ports:
      - 80:80
    environment:
      - PINGATUS_CONFIG_PATH=/config.yaml
    volumes:
      - ./config.yaml:/config.yaml

volumes:
  mongodata: