networks:
  mynet:
    driver: bridge

services:
  db:
    image: mongo:7.0
    restart: always
    networks:
      - mynet
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: