name: deploy

on:
  push:
    branches:
      - main
    paths:
      - 'assets/**'
      - './.github/workflows/ci-site.yml'
  pull_request:
    paths:
      - 'assets/**'
      - './.github/workflows/ci-site.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Make archive
        run: tar -czf assets.tar.gz assets

      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.USERPASS }}
          scp: |
            ./assets.tar.gz => ${{ secrets.PATH }}
          last_ssh: |
            cd ${{ secrets.PATH }}
            sudo tar -xzf assets.tar.gz
            sudo find ${{ secrets.PATH }}/assets -type d -exec chmod 775 {} +
            sudo find ${{ secrets.PATH }}/assets -type f -exec chmod 664 {} +
            sudo chown -R ${{ secrets.USER }}:${{ secrets.USER }} ${{ secrets.PATH }}/assets
            sudo rm assets.tar.gz