name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Submit coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: cover.out

      - name: Generate Release Notes
        id: generate_release_notes
        run: |
          git fetch origin --tags

          PREVIOUS_TAG=$(git describe --tags --abbrev=0 --always $(git rev-list --tags --skip=1 --max-count=1))

          COMMITS=$(git log $PREVIOUS_TAG..HEAD --oneline)

          if [ -z "$COMMITS" ]; then
            echo "initial release" > notes.txt
          else
            echo "$COMMITS" > notes.txt
          fi

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build binary
        env:
          GOBIN: /home/runner/go/bin
          GOFLAGS: "-mod=vendor"
        run: |
          go install github.com/adobromilskiy/pingatus/cmd/pingatus
          mv /home/runner/go/bin/pingatus /home/runner/go/bin/pingatus-${{ github.ref_name }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          bodyFile: notes.txt
          draft: false
          prerelease: false
          token: ${{ secrets.GITPKG_TOKEN }}
          artifacts: "/home/runner/go/bin/*"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        env:
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo ${{ secrets.GITPKG_TOKEN }} | docker login ghcr.io -u ${USERNAME} --password-stdin
          docker buildx build --push --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ github.repository }}:latest \
            -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .
