name: build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE v1.59.0

    - name: Run linters
      run: $GITHUB_WORKSPACE/golangci-lint run ./...

    - name: Run tests
      run: |
        docker run -tid --name testmongo -p 27117:27017 mongo:7.0
        go test -mod=vendor -covermode=count ./...
        docker rm -f testmongo

    - name: Test
      run: go test -mod=vendor -covermode=count ./... -coverprofile $GITHUB_WORKSPACE/cover.out

    - name: Submit coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push latest image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        echo ${{ secrets.GITPKG_TOKEN }} | docker login ghcr.io -u ${USERNAME} --password-stdin
        docker buildx build --push --platform linux/amd64,linux/arm64 \
          -t ghcr.io/${{ github.repository }}:latest .

    - name: Build and push tagged image
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      env:
        USERNAME: ${{ secrets.USERNAME }}
        GITHUB_REF: ${{ github.ref}}
      run: |
        ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
        echo GITHUB_REF - $ref
        echo ${{ secrets.GITPKG_TOKEN }} | docker login ghcr.io -u ${USERNAME} --password-stdin
        docker buildx build --push --platform linux/amd64,linux/arm64 \
          -t ghcr.io/${{ github.repository }}:${ref} .